Repository Rapter1990/parkinglot, pull requests merged in 2024-04, with the labels that each got.

#28 PR : Issue 14 : Get Parking Detail by Vehicle
  src/main/java/com/project/parkinglot/controller/VehicleController.java
  src/main/java/com/project/parkinglot/model/dto/response/ParkDetailResponse.java
  src/main/java/com/project/parkinglot/model/dto/response/VehicleParkingDetailResponse.java
  src/main/java/com/project/parkinglot/model/mapper/park/ParkEntityToParkDetailResponse.java
  src/main/java/com/project/parkinglot/service/vehicle/VehicleService.java
  src/main/java/com/project/parkinglot/service/vehicle/impl/VehicleServiceImpl.java
  src/test/java/com/project/parkinglot/builder/ParkEntityBuilder.java
  src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
  src/test/java/com/project/parkinglot/service/vehicle/impl/VehicleServiceImplTest.java
Labels: review

#30 PR : Issue #12 : Check out
  src/main/java/com/project/parkinglot/controller/ParkController.java
  src/main/java/com/project/parkinglot/model/dto/request/park/ParkCheckOutRequest.java
  src/main/java/com/project/parkinglot/model/dto/response/park/ParkCheckInResponse.java
  src/main/java/com/project/parkinglot/model/dto/response/park/ParkCheckOutResponse.java
  src/main/java/com/project/parkinglot/model/dto/response/vehicle/VehicleCheckInResponse.java
  src/main/java/com/project/parkinglot/model/dto/response/vehicle/VehicleCheckOutResponse.java
  src/main/java/com/project/parkinglot/model/entity/ParkingAreaEntity.java
  src/main/java/com/project/parkinglot/model/mapper/park/ParkEntityToParkCheckOutResponseMapper.java
  src/main/java/com/project/parkinglot/model/mapper/park/ParkToParkCheckInResponseMapper.java
  src/main/java/com/project/parkinglot/model/mapper/parking_area/ParkingAreaCreateRequestToParkingAreaEntityMapper.java
  src/main/java/com/project/parkinglot/model/mapper/parking_area/ParkingAreaEntityToParkingAreaMapper.java
  src/main/java/com/project/parkinglot/repository/ParkRepository.java
  src/main/java/com/project/parkinglot/service/park/ParkService.java
  src/main/java/com/project/parkinglot/service/park/impl/ParkServiceImpl.java
  src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaCreateServiceImpl.java
  src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
  src/main/java/com/project/parkinglot/service/vehicle/VehicleService.java
  src/main/java/com/project/parkinglot/service/vehicle/impl/VehicleServiceImpl.java
  src/main/java/com/project/parkinglot/utils/price/FeeCalculationUtil.java
  src/main/resources/application.yml
  src/test/java/com/project/parkinglot/builder/ParkCheckOutRequestBuilder.java
  src/test/java/com/project/parkinglot/builder/ParkEntityBuilder.java
  src/test/java/com/project/parkinglot/controller/ParkControllerTest.java
  src/test/java/com/project/parkinglot/service/park/impl/ParkServiceImplTest.java
  src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaCreateServiceImplTest.java
Labels: done

#31 Issue 15 (Part 1) - Last Check and Refactor
  pom.xml
  src/main/java/com/project/parkinglot/config/OpenApiConfig.java
  src/test/java/com/project/parkinglot/config/OpenApiConfigTest.java
Labels: refactor, review

#32 PR : Issue #13 : Get Daily Income of A Parking Area
  src/main/java/com/project/parkinglot/controller/AuthController.java
  src/main/java/com/project/parkinglot/controller/ParkController.java
  src/main/java/com/project/parkinglot/controller/ParkingAreaController.java
  src/main/java/com/project/parkinglot/controller/PriceListController.java
  src/main/java/com/project/parkinglot/controller/UserController.java
  src/main/java/com/project/parkinglot/controller/VehicleController.java
  src/main/java/com/project/parkinglot/exception/parkingarea/DailyIncomeException.java
  src/main/java/com/project/parkinglot/exception/parkingarea/InvalidDateException.java
  src/main/java/com/project/parkinglot/exception/parkingarea/ParkingAreaAlreadyExistException.java
  src/main/java/com/project/parkinglot/logging/aop/LoggerAspectJ.java
  src/main/java/com/project/parkinglot/model/DailyIncome.java
  src/main/java/com/project/parkinglot/model/ParkingArea.java
  src/main/java/com/project/parkinglot/model/dto/request/park/ParkCheckOutRequest.java
  src/main/java/com/project/parkinglot/model/dto/response/park/ParkCheckInResponse.java
  src/main/java/com/project/parkinglot/model/dto/response/park/ParkCheckOutResponse.java
  src/main/java/com/project/parkinglot/model/dto/response/parkingarea/ParkingAreaIncomeResponse.java
  src/main/java/com/project/parkinglot/model/dto/response/vehicle/VehicleCheckInResponse.java
  src/main/java/com/project/parkinglot/model/dto/response/vehicle/VehicleCheckOutResponse.java
  src/main/java/com/project/parkinglot/model/entity/DailyIncomeEntity.java
  src/main/java/com/project/parkinglot/model/entity/ParkingAreaEntity.java
  src/main/java/com/project/parkinglot/repository/DailyIncomeRepository.java
  src/main/java/com/project/parkinglot/repository/ParkingAreaRepository.java
  src/main/java/com/project/parkinglot/service/park/impl/ParkServiceImpl.java
  src/main/java/com/project/parkinglot/service/parking_area/ParkingAreaGetService.java
  src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaGetServiceImpl.java
  src/main/java/com/project/parkinglot/utils/price/FeeCalculationUtil.java
  src/main/resources/db/changelog/changes/1-parking-lot-ddl.xml
  src/main/resources/db/changelog/changes/7-daily-income-dml.xml
  src/test/java/com/project/parkinglot/builder/DailyIncomeBuilder.java
  src/test/java/com/project/parkinglot/builder/DailyIncomeEntityBuilder.java
  src/test/java/com/project/parkinglot/builder/ParkEntityBuilder.java
  src/test/java/com/project/parkinglot/builder/ParkingAreaBuilder.java
  src/test/java/com/project/parkinglot/builder/ParkingAreaEntityBuilder.java
  src/test/java/com/project/parkinglot/builder/ParkingAreaIncomeResponseBuilder.java
  src/test/java/com/project/parkinglot/config/OpenApiConfigTest.java
  src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
  src/test/java/com/project/parkinglot/service/park/impl/ParkServiceImplTest.java
  src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaGetServiceImplTest.java
  src/test/java/com/project/parkinglot/utils/TestUtilityClass.java
Labels: review
